"""Generate JSON schema and TypeScript from the same Pydantic source; no app/env import."""
from pathlib import Path
import json, sys
root = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(root))
from backend import r3_contracts as r3
names = ["ClarificationQuestion", "PlaceRef", "Evidence", "RouteCostResult", "TourRequest", "TourStop", "TourPlan", "StopProgress", "TourSession", "PlanRevision", "TourCommand", "TourRestore", "TourResult", "RouteCostRequest", "RouteCostResponse", "SpeechInteractionEvent", "EvaluationRecord"]
schemas = {name: getattr(r3, name).model_json_schema() for name in names}
bundle = {"contract_version": r3.R3_CONTRACT_VERSION, "schemas": schemas}
definitions = {}
for schema in schemas.values():
    definitions.update(schema.get("$defs", {}))
definitions.update(schemas)
def ts(s):
    if "$ref" in s: return s["$ref"].split("/")[-1]
    if "const" in s: return json.dumps(s["const"], ensure_ascii=False)
    if "enum" in s: return " | ".join(json.dumps(v, ensure_ascii=False) for v in s["enum"])
    if "anyOf" in s: return " | ".join(ts(v) for v in s["anyOf"])
    kind = s.get("type")
    if kind == "object":
        required = s.get("required", [])
        return "{ " + " ".join(k + ("" if k in required else "?") + ": " + ts(v) + ";" for k, v in s.get("properties", {}).items()) + " }"
    if kind == "array": return "Array<" + ts(s["items"]) + ">"
    return {"string": "string", "integer": "number", "number": "number", "boolean": "boolean", "null": "null"}[kind]
ts_output = "// Generated by scripts/export-r3-schema.py. M-owned; runtime validation is server-side.\nexport const R3_CONTRACT_VERSION = '1.2.0' as const;\n"
ts_output += "\n".join("export type " + n + " = " + ts(s) + ";" for n, s in sorted(definitions.items())) + "\n"
outputs = {"shared/r3.schema.json": json.dumps(bundle, ensure_ascii=False, indent=2) + "\n", "shared/r3.ts": ts_output}
for name, data in outputs.items():
    if "--check" in sys.argv:
        assert (root / name).read_text(encoding="utf-8") == data, "Schema drift: " + name
    else:
        (root / name).write_text(data, encoding="utf-8")
print("R3 schema/types " + ("checked" if "--check" in sys.argv else "exported"))