"""Independent coordination schema/type export. Works directly on r3-launch."""
from pathlib import Path
import json,sys
root=Path(__file__).resolve().parents[1];sys.path.insert(0,str(root))
from backend.r3_knowledge_contracts import ApplicableEvidence,TourKnowledgeContext
schemas={c.__name__:c.model_json_schema() for c in (ApplicableEvidence,TourKnowledgeContext)}
definitions={}
for schema in schemas.values():definitions.update(schema.get("$defs",{}))
definitions.update(schemas)
def ts(s):
    if "$ref" in s:return s["$ref"].split("/")[-1]
    if "const" in s:return json.dumps(s["const"])
    if "enum" in s:return " | ".join(json.dumps(v) for v in s["enum"])
    if "anyOf" in s:return " | ".join(ts(v) for v in s["anyOf"])
    kind=s.get("type")
    if kind=="object":
        return "{ "+" ".join(k+("" if k in s.get("required",[]) else "?")+": "+ts(v)+";" for k,v in s.get("properties",{}).items())+" }"
    if kind=="array":return "Array<"+ts(s["items"])+">"
    return {"string":"string","integer":"number","number":"number","boolean":"boolean","null":"null"}[kind]
outputs={"shared/r3-knowledge.schema.json":json.dumps({"contract_version":"1.2.0","schemas":schemas},ensure_ascii=False,indent=2)+"\n",
 "shared/r3-knowledge.ts":"// Generated by scripts/export-r3-knowledge-schema.py. M-owned.\n"+"\n".join("export type "+k+" = "+ts(v)+";" for k,v in sorted(definitions.items()))+"\n"}
for path,data in outputs.items():
    if "--check" in sys.argv:assert (root/path).read_text(encoding="utf-8")==data,"Schema drift: "+path
    else:(root/path).write_text(data,encoding="utf-8")
print("R3 knowledge schema/types checked" if "--check" in sys.argv else "R3 knowledge schema/types exported")