import {useEffect,useRef,useState} from 'react';
import type {CampusId} from '../../../shared/contracts';
import {reconstructionApi,reconstructionToken,modelDownload,startReconstructionTask,type ModelAsset,type ModelLayout,type ReconstructionState} from '../transport/reconstruction';
import {pickModelPoint,referenceDistance,showModelsOnMap,focusModelMap,locateModelPoi,adjustModelMap} from '../scene/reconstruction-map';
import * as THREE from 'three';
import {GLTFLoader} from 'three/examples/jsm/loaders/GLTFLoader.js';
import {OrbitControls} from 'three/examples/jsm/controls/OrbitControls.js';
import './reconstruction.css';
const LABELS:Record<string,string>={queued:'排队中',preprocessing:'处理图片',loading:'加载权重',reconstructing:'GPU重建中',exporting:'导出网格',validating:'验证GLB',succeeded:'已完成',failed:'失败',cancelled:'已取消',planning:'GLM规划工具',waiting_jobs:'等待重建完成后自动继续',waiting_calibration:'请完成地图位置和参考长度标定，任务会自动继续',waiting_scene:'等待地图实际显示回执',partial:'部分完成'};
function ModelViewer({asset}:{asset:ModelAsset}){
 const host=useRef<HTMLDivElement>(null),controls=useRef<OrbitControls|null>(null),camera=useRef<THREE.PerspectiveCamera|null>(null),draw=useRef<()=>void>(()=>{});const [error,setError]=useState('');
 useEffect(()=>{let disposed=false,release=()=>{};setError('');void(async()=>{const token=await reconstructionToken();const gltf=await new GLTFLoader().setRequestHeader({'X-Reconstruction-Session':token}).loadAsync(`/api/reconstruction/assets/${asset.id}/file?v=${asset.sha256}`);if(disposed)return;
  const scene=new THREE.Scene();scene.background=new THREE.Color('#edf2f1');scene.add(new THREE.HemisphereLight(0xffffff,0x999999,2));const light=new THREE.DirectionalLight(0xffffff,2);light.position.set(3,5,4);scene.add(light);scene.add(gltf.scene);const box=new THREE.Box3().setFromObject(gltf.scene),center=box.getCenter(new THREE.Vector3()),size=Math.max(...asset.extents);gltf.scene.position.sub(center);
  const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));host.current!.appendChild(renderer.domElement);const cam=new THREE.PerspectiveCamera(45,1,.01,1000);cam.position.set(size,size*.6,size*1.7);camera.current=cam;const orbit=new OrbitControls(cam,renderer.domElement);controls.current=orbit;orbit.enableDamping=false;
  const render=()=>{if(disposed||!host.current)return;const w=host.current.clientWidth,h=320;renderer.setSize(w,h);cam.aspect=w/h;cam.updateProjectionMatrix();orbit.update();renderer.render(scene,cam);renderer.domElement.dataset.assetId=asset.id;};draw.current=render;orbit.addEventListener('change',()=>renderer.render(scene,cam));const ro=new ResizeObserver(render);ro.observe(host.current!);render();release=()=>{ro.disconnect();orbit.dispose();scene.traverse(o=>{const m=o as THREE.Mesh;m.geometry?.dispose();(Array.isArray(m.material)?m.material:[m.material]).forEach(x=>x?.dispose());});renderer.dispose();renderer.domElement.remove();};
 })().catch(e=>setError(String(e)));return()=>{disposed=true;release();};},[asset.id,asset.sha256]);
 return <section><div className="model-viewer" ref={host}/>{error&&<p role="alert">{error}</p>}<div className="model-actions">{['正面','侧面','背面','复位'].map((s,i)=><button key={s} onClick={()=>{const c=camera.current;if(!c)return;const n=Math.max(...asset.extents)*2;controls.current!.target.set(0,0,0);c.position.set(i===1?n:i===3?n*.6:0,n*.25,i===2?-n:i===1?0:n);draw.current();}}>{s}</button>)}</div><small>拖动旋转，滚轮缩放。单图背面与遮挡部分由模型推断。</small></section>;
}
export function ReconstructionPanel({campus}:{campus:CampusId}){
 const [open,setOpen]=useState(()=>localStorage.getItem("ai4tju.reconstruction.open")==="1"),[state,setState]=useState<ReconstructionState>({ready:false,images:[],jobs:[],assets:[],layouts:[],runs:[]}),[catalog,setCatalog]=useState<any[]>([]),[photo,setPhoto]=useState(''),[poi,setPoi]=useState(''),[selected,setSelected]=useState(''),[error,setError]=useState(''),[note,setNote]=useState(''),[prompt,setPrompt]=useState(''),[background,setBackground]=useState(true);
 const [anchor,setAnchor]=useState<[number,number]|null>(null),[heading,setHeading]=useState(0),[length,setLength]=useState(''),[axis,setAxis]=useState('width'),[source,setSource]=useState(''),[points,setPoints]=useState<[number,number][]|null>(null);
 const applying=useRef(''),applied=useRef(''),stateRef=useRef(state);stateRef.current=state;
 useEffect(()=>{localStorage.setItem("ai4tju.reconstruction.open",open?"1":"0");},[open]);
 async function refresh(){try{setState(await reconstructionApi('/state'));}catch(e){setError(String(e));}}
 useEffect(()=>{const show=()=>setOpen(true);window.addEventListener('reconstruction-open',show);return()=>window.removeEventListener('reconstruction-open',show);},[]);
 useEffect(()=>{if(!open)return;void refresh();void reconstructionApi('/catalog/'+campus).then(c=>{setCatalog(c);setPhoto(c[0]?.id??'');setPoi(c[0]?.poiId??'');});const t=setInterval(()=>void refresh(),1800);return()=>clearInterval(t);},[open,campus]);
 const assets=state.assets.filter(a=>a.campusId===campus),asset=assets.find(a=>a.id===selected)??assets.at(-1);
 const layout=state.layouts.find(l=>l.assetId===asset?.id);
 useEffect(()=>{setAnchor(layout?.anchorLngLat??null);setHeading(layout?.headingDeg??0);setLength(layout?String(layout.reference.lengthM):'');setAxis(layout?.reference.axis??'width');setSource(layout?.reference.source??'');setPoints(layout?.reference.points??null);},[asset?.id,layout?.revision]);
 async function action(fn:()=>Promise<unknown>){setError('');try{await fn();await refresh();}catch(e){setError(e instanceof Error?e.message:String(e));}}
 async function applyMap(manual=false){const s=stateRef.current;const aa=s.assets.filter(a=>a.campusId===campus&&s.layouts.some(l=>l.assetId===a.id));if(!aa.length)return;const ll=s.layouts.filter(l=>aa.some(a=>a.id===l.assetId));const key=ll.map(l=>l.assetId+':'+l.revision).join(',');if(applying.current===key)return;if(!manual&&applied.current===key){await ackExisting(s,ll);return;}applying.current=key;
  try{await showModelsOnMap(aa,ll,()=>{});applied.current=key;await ackExisting(s,ll);if(manual)focusModelMap();setNote('三维建筑已叠加到在线地图，可旋转和倾斜地图检查。');}finally{applying.current='';}}
 async function ackExisting(s:ReconstructionState,ll:ModelLayout[]){for(const run of s.runs.filter(r=>r.campusId===campus&&r.stage==='waiting_scene'))for(const l of ll)if(run.sceneRequest?.revisions[l.assetId]===l.revision&&run.applied?.[l.assetId]!==l.revision)await reconstructionApi(`/runs/${run.id}/ack`,{assetId:l.assetId,revision:l.revision,scope:'map_drawn'});}
 useEffect(()=>{if(open&&state.layouts.length)void applyMap().catch(()=>{});},[state,open,campus]);
 useEffect(()=>{const ready=()=>{applied.current='';void applyMap().catch(()=>{});};window.addEventListener('reconstruction-map-ready',ready);return()=>window.removeEventListener('reconstruction-map-ready',ready);},[campus]);
 return <section className="reconstruction-panel"><button className="model-open" onClick={()=>setOpen(!open)}>建筑建模与三维地图 {open?'收起':'打开'}</button>{open&&<div className="model-body"><h3>图片还原建筑</h3><p>选择校园照片或上传JPEG/PNG；原图保留。生成结果需要对照照片检查，隐藏面为推断。</p><p role="status">{state.ready?'TripoSR 环境已就绪 · 单GPU顺序处理':'重建环境准备中，暂不能提交推理'}</p>
 <div className="model-actions"><select aria-label="建筑照片" value={photo} onChange={e=>{setPhoto(e.target.value);setPoi(catalog.find(p=>p.id===e.target.value)?.poiId??'');}}>{catalog.map(p=><option key={p.id} value={p.id}>{p.poiId} · {p.id.split(':').at(-1)}</option>)}</select><button onClick={()=>void action(async()=>{const im=await reconstructionApi('/images/import',{photoId:photo,campusId:campus});await reconstructionApi('/jobs',{imageId:im.id,idempotencyKey:crypto.randomUUID(),removeBackground:background});})} disabled={!state.ready||!photo}>用此照片生成</button></div>
 {photo&&<img className="model-source" src={catalog.find(p=>p.id===photo)?.url} alt="选中的建模原图"/>}
 <label>上传图片所属地点<select aria-label="上传图片所属地点" value={poi} onChange={e=>setPoi(e.target.value)}>{[...new Set(catalog.map(p=>p.poiId))].map(id=><option key={id}>{id}</option>)}</select></label>
 <label>上传 JPEG/PNG<input aria-label="上传建筑图片" type="file" accept="image/jpeg,image/png" onChange={e=>{const file=e.target.files?.[0];if(!file)return;void action(async()=>{if(file.size>8*1024*1024)throw Error('图片最多8MiB');const bytes=new Uint8Array(await file.arrayBuffer());let binary='';for(const b of bytes)binary+=String.fromCharCode(b);const im=await reconstructionApi('/images',{filename:file.name,contentBase64:btoa(binary),poiId:poi,campusId:campus});setNote('图片已解码导入：'+im.filename);});}}/></label>
 <label><input type="checkbox" checked={background} onChange={e=>setBackground(e.target.checked)}/>去除背景（主体被误删时可关闭并换图）</label>
 <div className="model-actions">{state.images.filter(i=>i.campusId===campus&&i.source==='user upload').map(i=><button key={i.id} disabled={!state.ready} onClick={()=>void action(()=>reconstructionApi('/jobs',{imageId:i.id,idempotencyKey:crypto.randomUUID(),removeBackground:background}))}>生成：{i.filename}</button>)}</div>
 <label>让 Agent 完成多步任务<textarea aria-label="建模任务指令" value={prompt} onChange={e=>setPrompt(e.target.value)} placeholder="用已有的郑东图书馆和大通学生中心照片分别生成模型，按地图位置摆放，展示模型并提供下载，标出估计的尺寸。"/></label><button disabled={!prompt.trim()||!state.ready} onClick={()=>void action(()=>startReconstructionTask(prompt,campus))}>执行建模任务</button>
 {state.runs.filter(r=>r.campusId===campus).slice(-3).map(r=><article className="model-job" key={r.id} data-run-id={r.id} data-stage={r.stage}><strong>{LABELS[r.stage]??r.stage}</strong><p>{r.intent}</p><small>模型 {r.modelCalls}/8 · 工具 {r.toolCalls}/24</small><p>{r.error??r.answer}</p>{!['succeeded','failed','cancelled','partial'].includes(r.stage)&&<button onClick={()=>void action(()=>reconstructionApi(`/runs/${r.id}/cancel`,{}))}>取消建模任务</button>}<details><summary>实际工具执行记录</summary>{r.trace?.filter((t:any)=>t.event==='model_selection'||t.event==='tool_result'||t.event==='client_applied').map((t:any,i:number)=><pre key={i}>{JSON.stringify(t,null,2)}</pre>)}</details></article>)}
 {state.jobs.filter(j=>j.campusId===campus).map(j=><article className="model-job" key={j.id} data-job-id={j.id} data-stage={j.stage}><strong>{j.poiId}：{LABELS[j.stage]??j.stage}</strong><p>{j.cancelRequested&&j.stage!=='cancelled'?'取消处理中，当前GPU阶段结束后丢弃发布结果。':j.error}</p>{!['succeeded','failed','cancelled'].includes(j.stage)&&<button onClick={()=>void action(()=>reconstructionApi(`/jobs/${j.id}/cancel`,{}))}>取消生成</button>}</article>)}
 {asset&&<><h3>已生成建筑</h3><select aria-label="查看生成模型" value={asset.id} onChange={e=>setSelected(e.target.value)}>{assets.map(a=><option value={a.id} key={a.id}>{a.poiId} · {a.id.slice(-6)}</option>)}</select><ModelViewer asset={asset}/><button onClick={()=>void action(()=>modelDownload(asset))}>下载当前建筑 GLB</button><p>{asset.vertices} 顶点 · {asset.faces} 三角面。{asset.quality}</p><h4>地图位置与尺度标定</h4><p>在原在线地图选建筑位置，并标一条对应模型宽/深/高的参考长度。尺寸由该参考推算，不代表测绘实测。</p><div className="model-actions"><button onClick={()=>void action(async()=>{setNote('请在在线地图上点击建筑锚点');setAnchor(await pickModelPoint());})}>在地图选择建筑位置</button><button onClick={()=>void action(async()=>{setAnchor(await locateModelPoi(asset.poiId));setNote("已定位地图匹配坐标，请核对建筑中心并标定参考边。");})}>定位地图中的该建筑</button><span>{anchor?.map(n=>n.toFixed(6)).join(', ')??'尚未标定位置'} · GCJ-02</span></div><div className="model-actions"><button onClick={()=>void action(async()=>{setNote('请在在线地图依次点击建筑参考边的两个端点');const a=await pickModelPoint(),b=await pickModelPoint();setPoints([a,b]);setLength(referenceDistance(a,b).toFixed(2));setSource('用户在高德GCJ-02地图选择参考边；球面距离估计');})}>地图量测参考边</button><select aria-label="参考长度对应轴" value={axis} onChange={e=>setAxis(e.target.value)}><option value="width">模型宽</option><option value="depth">模型深</option><option value="height">模型高</option></select></div><label>参考长度（米）<input aria-label="参考长度米" type="number" min="0.1" value={length} onChange={e=>{setLength(e.target.value);setPoints(null);}}/></label><label>参考长度依据<input aria-label="参考长度依据" value={source} onChange={e=>setSource(e.target.value)} placeholder="填写实际资料、用户测量或地图量测依据"/></label><label>朝向（从北顺时针）<input aria-label="建筑朝向" type="number" min="-360" max="360" value={heading} onChange={e=>setHeading(Number(e.target.value))}/></label><div className="model-actions"><button disabled={!anchor||!Number(length)||source.length<3} onClick={()=>void action(()=>reconstructionApi('/layouts',{assetId:asset.id,anchorLngLat:anchor,anchorSource:'用户在地图确认建筑展示锚点，非导航入口',headingDeg:heading,referenceLengthM:Number(length),referenceAxis:axis,referenceSource:source,referencePoints:points,revision:layout?.revision??0},'PUT'))}>保存位置、尺度与朝向</button><button onClick={()=>void action(()=>applyMap(true))}>在地图展示已标定建筑</button>{(['pan','rotate','pitch','zoom'] as const).map((mode,i)=><button key={mode} onClick={()=>void action(async()=>adjustModelMap(mode))}>{['平移地图','旋转地图45°','俯视/倾斜地图','放大地图'][i]}</button>)}<button onClick={()=>{setAnchor(layout?.anchorLngLat??null);setHeading(layout?.headingDeg??0);setLength(layout?String(layout.reference.lengthM):'');setSource(layout?.reference.source??'');}}>恢复已保存标定</button></div>{layout&&<p>参考估计：宽 {layout.dimensionsM.width.toFixed(1)}m / 深 {layout.dimensionsM.depth.toFixed(1)}m / 高 {layout.dimensionsM.height.toFixed(1)}m；除参考轴外均由生成网格比例推算。版本 {layout.revision}</p>}</>}
 {note&&<p role="status">{note}</p>}{error&&<p role="alert">{error}</p>}</div>}</section>;
}
