import {useEffect,useState} from 'react';
import type {CampusId} from '../../../shared/contracts';
import {reconstructionApi,reconstructionToken,rememberReconstruction,type ReconstructionState} from '../transport/reconstruction';
type GroupImage={key:string;imageId?:string;photoId?:string;url?:string;name:string;poiId:string|null;sourceUrl?:string};
type Props={campus:CampusId;catalog:any[];state:ReconstructionState;onSubmitted:(job:any)=>void;onError:(message:string)=>void;demo?:{title:string;sourceImages:{url:string;title?:string;sourceUrl?:string}[]};onViewDemo?:()=>void};
function GroupThumbnail({item}:{item:GroupImage}){const [src,setSrc]=useState(item.url??'');useEffect(()=>{let dead=false,link='';if(!item.imageId)return;void(async()=>{const token=await reconstructionToken(),r=await fetch(`/api/reconstruction/images/${item.imageId}`,{headers:{'X-Reconstruction-Session':token}});if(!r.ok)return;link=URL.createObjectURL(await r.blob());if(dead)URL.revokeObjectURL(link);else setSrc(link);})().catch(()=>{});return()=>{dead=true;if(link)URL.revokeObjectURL(link);};},[item.imageId]);return src?<img src={src} alt={item.name}/>:<span>图片预览</span>;}
function sourceUrl(item:any){const value=item.sourceUrl??item.source?.url??item.url;try{const url=new URL(value,location.origin);return ['https:','http:'].includes(url.protocol)?url.href:undefined;}catch{return undefined;}}
export function ReconstructionMultiView({campus,catalog,state,onSubmitted,onError,demo,onViewDemo}:Props){
 const [images,setImages]=useState<GroupImage[]>([]),[poi,setPoi]=useState(''),[busy,setBusy]=useState(false),[status,setStatus]=useState(''),[inspection,setInspection]=useState<any>(null);
 const maximum=state.multiViewMaxViews??12,ready=state.multiViewReady??state.providers?.includes('depth-anything-3')??false;
 const places=[...new Map(catalog.map(p=>[p.poiId,p])).values()];const candidates=catalog.filter(p=>p.poiId===poi);
 useEffect(()=>{setImages([]);setPoi('');setInspection(null);setStatus('');},[campus]);
 function selectPoi(value:string){if(images.length&&images.some(i=>i.poiId!==value&&i.poiId!==null)){onError('请先清空当前照片组，再选择另一处场景。');return;}setPoi(value);}
 function togglePhoto(p:any){setInspection(null);if(images.some(i=>i.photoId===p.id)){setImages(current=>current.filter(i=>i.photoId!==p.id));return;}if(images.length>=maximum){onError(`一组最多 ${maximum} 张图片`);return;}setImages(current=>[...current,{key:p.id,photoId:p.id,url:p.url,name:p.title??p.poiName??p.id,poiId:p.poiId,sourceUrl:sourceUrl(p)}]);}
 async function loadDemo(){if(!demo)return;setBusy(true);setInspection(null);onError('');try{const imported:GroupImage[]=[];for(let n=0;n<demo.sourceImages.length;n+=2){const group=await Promise.all(demo.sourceImages.slice(n,n+2).map(async(p,index)=>{const response=await fetch(p.url);if(!response.ok)throw Error('演示照片加载失败');const bytes=new Uint8Array(await response.arrayBuffer());let binary='';for(const b of bytes)binary+=String.fromCharCode(b);const filename=new URL(p.url,location.origin).pathname.split('/').pop()??`view-${n+index+1}.png`;const im=await reconstructionApi('/images',{filename,contentBase64:btoa(binary),poiId:null,campusId:campus});rememberReconstruction('images',im.id);return {key:im.id,imageId:im.id,url:p.url,name:p.title??`${demo.title} · 视角 ${n+index+1}`,poiId:null,sourceUrl:p.sourceUrl} as GroupImage;}));imported.push(...group);}setImages(imported);setPoi('');setStatus('已导入经过融合验证的双视角输入。点击重建将提交一次新的实际任务。');}catch(e){onError(e instanceof Error?e.message:String(e));}finally{setBusy(false);}}

 async function upload(files:File[]){if(!files.length)return;if(images.length+files.length>maximum){onError(`一组最多 ${maximum} 张图片，请减少选择数量。`);return;}setBusy(true);setInspection(null);onError('');let imported=0;const failed:string[]=[];
  try{for(let n=0;n<files.length;n+=2){const results=await Promise.allSettled(files.slice(n,n+2).map(async file=>{if(file.size>8*1024*1024)throw Error(`${file.name} 超过8MiB`);const bytes=new Uint8Array(await file.arrayBuffer());let binary='';for(const b of bytes)binary+=String.fromCharCode(b);const im=await reconstructionApi('/images',{filename:file.name,contentBase64:btoa(binary),poiId:poi||null,campusId:campus});rememberReconstruction('images',im.id);return {key:im.id,imageId:im.id,name:im.filename,poiId:im.poiId??null} as GroupImage;}));for(const result of results)if(result.status==='fulfilled'){imported++;setImages(current=>[...current,result.value]);}else failed.push(result.reason instanceof Error?result.reason.message:String(result.reason));setStatus(`已导入 ${imported} / ${files.length} 张图片`);}if(failed.length)onError(failed.join('；'));}finally{setBusy(false);}}
 async function inputIds(){const ids:string[]=[];for(const item of images){if(item.imageId)ids.push(item.imageId);else{const im=await reconstructionApi('/images/import',{photoId:item.photoId,campusId:campus});ids.push(im.id);}}return ids;}
 async function inspect(){setBusy(true);onError('');try{const imageIds=await inputIds();setInspection(await reconstructionApi('/image-groups/inspect',{imageIds}));setStatus('已完成照片组重叠检查；相机与几何质量仍以实际重建为准。');}catch(e){onError(e instanceof Error?e.message:String(e));}finally{setBusy(false);}}
 async function submit(){setBusy(true);onError('');try{const imageIds=await inputIds();const job=await reconstructionApi('/jobs',{imageIds,idempotencyKey:crypto.randomUUID(),generator:'auto',removeBackground:false,quality:'standard'});rememberReconstruction('jobs',job.id);setStatus(job.cacheHit?'已复用此照片组的已有结果。':'多图任务已提交；会按实际相机与表面重建结果报告。');onSubmitted(job);}catch(e){onError(e instanceof Error?e.message:String(e));}finally{setBusy(false);}}
 return <div className="model-multiview">{demo&&demo.sourceImages.length>=2&&<section className="model-demo"><small>已通过融合检查的真实双视角示例</small><h4>{demo.title}</h4><p>输入照片、恢复相机与统一表面可对照查看；结果只覆盖实际观测表面。</p><button disabled={busy} onClick={()=>void loadDemo()}>载入已验证的双视角示例</button><button onClick={onViewDemo}>查看已生成融合结果</button>{demo.sourceImages[0]?.sourceUrl&&<a href={demo.sourceImages[0].sourceUrl} target="_blank" rel="noreferrer">查看照片来源</a>}</section>}<p className="model-muted">围绕同一个物体或场景拍摄，邻近照片应有重叠内容。保留原始背景，避免重复图片。结果只覆盖实际重建出的表面。</p><label>场景地点（可选）<select aria-label="多图场景地点" value={poi} disabled={busy} onChange={e=>selectPoi(e.target.value)}><option value="">通用物体 / 不绑定地点</option>{places.map((p:any)=><option key={p.poiId} value={p.poiId}>{p.poiName??p.poiId}</option>)}</select></label>
 <label className="model-upload">添加同场景照片<input aria-label="上传多视角图片" type="file" multiple accept="image/jpeg,image/png" disabled={busy} onChange={e=>{const files=Array.from(e.target.files??[]);e.target.value='';void upload(files);}}/><small>2–{maximum} 张 JPEG / PNG，每张最多 8 MiB</small></label>
 {candidates.length>0&&<details className="model-group-catalog" open><summary>选择已有场景照片（{candidates.length} 张）</summary><div className="model-group-candidates">{candidates.map((p,index)=><button type="button" className={images.some(i=>i.photoId===p.id)?'is-selected':''} aria-pressed={images.some(i=>i.photoId===p.id)} aria-label={`选择视角 ${index+1}`} key={p.id} disabled={busy} onClick={()=>togglePhoto(p)}><img src={p.url} alt={`${p.poiName??p.poiId} 视角 ${index+1}`}/><span>视角 {index+1}</span></button>)}</div><small>请选同一建筑有重叠区域的视角；不同建筑不能合并成一组。</small></details>}
 <div className="model-group-heading"><strong>本组 {images.length} / {maximum} 张</strong>{images.length>0&&<button disabled={busy} onClick={()=>{setImages([]);setInspection(null);setStatus('');}}>清空照片组</button>}</div>
 {images.length>0?<ol className="model-group-images">{images.map((item,index)=><li key={item.key}><GroupThumbnail item={item}/><div><strong>{index+1}. {item.name}</strong>{item.sourceUrl&&<a href={item.sourceUrl} target="_blank" rel="noreferrer">查看来源</a>}</div><button disabled={busy} aria-label={`移除第 ${index+1} 张图片`} onClick={()=>{setImages(current=>current.filter(i=>i.key!==item.key));setInspection(null);}}>移除</button></li>)}</ol>:<p className="model-group-empty">添加多个重叠视角，或选择已有场景照片。</p>}
 <button disabled={busy||images.length<2} onClick={()=>void inspect()}>检查照片重叠</button>{inspection&&<div className="model-observation"><strong>照片重叠检查：{({connected:'有连续重叠',disconnected:'存在不相连视角',duplicate_only:'只有重复图片',insufficient_overlap:'重叠不足'} as Record<string,string>)[inspection.status]??inspection.status}</strong>{inspection.warnings?.map((w:string)=><p key={w}>{w}</p>)}{inspection.recommendations?.map((w:string)=><p key={w}>{w}</p>)}<small>重叠检查通过不等于已恢复相机或可信三维表面。</small></div>}<button className="model-primary" disabled={busy||!ready||images.length<2||images.length>maximum} onClick={()=>void submit()}>{busy?'正在整理照片组…':'从这组照片重建'}</button><p className="model-service" role="status">{status||(ready?'多图重建可用；不完整视角会保留覆盖限制。':'多图模型尚未就绪，可以先整理照片组。')}</p>
 </div>;
}
